# Generated by Django 5.0.6 on 2024-07-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_id', models.CharField(max_length=255)),
                ('branch_type', models.CharField(max_length=255)),
                ('branch_country', models.CharField(max_length=255)),
                ('branch_state', models.CharField(max_length=255)),
                ('branch_district', models.CharField(max_length=255)),
                ('branch_address', models.CharField(max_length=255)),
            ],
        ),
    ]
