# Generated by Django 5.0.6 on 2024-07-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_id',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
