# Generated by Django 5.0.6 on 2024-07-08 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_main', '0002_alter_branch_branch_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_category', models.CharField(max_length=255)),
                ('department_name', models.CharField(max_length=255)),
            ],
        ),
    ]
