# Generated by Django 5.0.6 on 2024-07-08 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_main', '0003_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='branch_category',
            new_name='department_category',
        ),
    ]
