# Generated by Django 5.0.6 on 2024-07-08 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_main', '0004_rename_branch_category_department_department_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='department_id',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
