# Generated by Django 5.0.6 on 2024-07-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_main', '0006_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leavs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_name', models.CharField(max_length=255)),
                ('days_per_year', models.CharField(max_length=255)),
            ],
        ),
    ]
