# Generated by Django 5.0.6 on 2024-07-08 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_main', '0007_leavs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Leavs',
            new_name='Leaves',
        ),
    ]
