# Generated by Django 5.0.6 on 2024-07-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_main', '0009_document_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payslip_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payslip_name', models.CharField(max_length=255)),
            ],
        ),
    ]
