# Generated by Django 5.0.6 on 2024-07-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_main', '0010_payslip_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allowance_option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowance_option_name', models.CharField(max_length=255)),
            ],
        ),
    ]
