# Generated by Django 5.0.6 on 2024-07-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_main', '0012_loan_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deduction_option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Deduction_option_name', models.CharField(max_length=255)),
            ],
        ),
    ]
