# Generated by Django 5.0.6 on 2024-07-10 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_main', '0013_deduction_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Award_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Competencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Competencies_name', models.CharField(max_length=255)),
                ('Competencies_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Contract_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contract_type_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Expence_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Expence_type_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Goal_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Goal_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Income_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Income_type_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Job_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_category_title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Job_stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_stage_title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Payment_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Payment_type_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Performance_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Performance_type_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Termination_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Termination', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Training_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Training_name', models.CharField(max_length=255)),
            ],
        ),
    ]
