# Generated by Django 5.0.6 on 2024-07-19 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_main', '0018_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role_name', models.CharField(max_length=255)),
                ('Module', models.CharField(max_length=255)),
                ('Permission', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
