# Generated by Django 5.0.6 on 2024-07-19 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_main', '0019_roles_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_id', models.CharField(max_length=255)),
                ('Employee_name', models.CharField(max_length=255)),
                ('Employee_phone', models.CharField(max_length=255)),
                ('Date_of_Birth', models.CharField(max_length=255)),
                ('Gender', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
                ('Branch', models.CharField(max_length=255)),
                ('Department', models.CharField(max_length=255)),
                ('Role', models.CharField(max_length=255)),
                ('Designation', models.CharField(max_length=255)),
                ('Date_Of_Joining', models.CharField(max_length=255)),
                ('Employee_type', models.CharField(max_length=255)),
                ('Document', models.CharField(max_length=255)),
                ('Account_holder', models.CharField(max_length=255)),
                ('Account_number', models.CharField(max_length=255)),
                ('Bank_name', models.CharField(max_length=255)),
                ('Bank_identifier_code', models.CharField(max_length=255)),
                ('Branch_location', models.CharField(max_length=255)),
                ('Tax_payer_id', models.CharField(max_length=255)),
            ],
        ),
    ]
