# Generated by Django 5.0.6 on 2024-07-23 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_main', '0023_roles_remove_rolepermission_module_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role_permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role_name', models.CharField(max_length=255)),
                ('Module', models.CharField(max_length=255)),
                ('Permission', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='roles',
            name='Module',
        ),
        migrations.RemoveField(
            model_name='roles',
            name='Permission',
        ),
    ]
