# Generated by Django 5.0.6 on 2024-07-23 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_main', '0024_role_permission_remove_roles_module_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrms_main.module')),
                ('permissions', models.ManyToManyField(to='hrms_main.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrms_main.role')),
            ],
        ),
        migrations.DeleteModel(
            name='Role_permission',
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
        migrations.AddField(
            model_name='role',
            name='modules',
            field=models.ManyToManyField(through='hrms_main.RolePermission', to='hrms_main.module'),
        ),
    ]
