# Generated by Django 5.0.6 on 2024-07-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_main', '0026_companypolicy_delete_company_policy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companypolicy',
            name='branch',
            field=models.CharField(max_length=255),
        ),
    ]
