# Generated by Django 5.0.6 on 2024-07-29 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_main', '0027_alter_companypolicy_branch'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Job_On_Boardind',
            new_name='Job_On_Boarding',
        ),
    ]
