# Generated by Django 5.0.6 on 2024-08-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_main', '0028_rename_job_on_boardind_job_on_boarding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Justtry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
