# Generated by Django 5.0.6 on 2024-08-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_main', '0031_alter_employee_employee_id_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_leaves',
            name='Employee_id',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
