# Generated by Django 5.0.6 on 2024-08-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_main', '0032_create_leaves_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='create_leaves',
            name='Employee',
        ),
        migrations.RemoveField(
            model_name='create_leaves',
            name='Leave_type',
        ),
        migrations.AlterField(
            model_name='create_leaves',
            name='Employee_id',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
