# Generated by Django 5.0.6 on 2024-08-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_main', '0033_remove_create_leaves_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_leaves',
            name='Leave_type',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
