# Generated by Django 5.0.6 on 2024-08-10 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_main', '0034_create_leaves_leave_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_leaves',
            name='Status',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
